from typing import Protocol, runtime_checkable

@runtime_checkable
class Callback(Protocol):
    def on_train_start(self, **kwargs) -> None: ...
    def on_train_end(self, **kwargs) -> None: ...
    def on_epoch_start(self, epoch: int, **kwargs) -> None: ...
    def on_epoch_end(self, epoch: int, **kwargs) -> None: ...
    def on_batch_start(self, step: int, **kwargs) -> None: ...
    def on_batch_end(self, step: int, **kwargs) -> None: ...

class CallbackBase:
    """No-op implementations so implementers can inherit and only override what they need."""
    def on_train_start(self, **kwargs) -> None: ...
    def on_train_end(self, **kwargs) -> None: ...
    def on_epoch_start(self, epoch: int, **kwargs) -> None: ...
    def on_epoch_end(self, epoch: int, **kwargs) -> None: ...
    def on_batch_start(self, step: int, **kwargs) -> None: ...
    def on_batch_end(self, step: int, **kwargs) -> None: ...